### ISSUE TITLE
Publish for mingwX64

### ISSUE THREAD

**Issue by mpetuska** [reduxkotlin/redux-kotlin#42]
Currently lib fails to resolve for mingwX64 target. This essentially means it's unviable for any MPP project using it.

**Comment by patjackson52** [comment]
Yes, I am aware.  Publishing to all platforms is a challenge.  I would like to get this automated.  I currently do not have access to a windows machine, so even manual publishing would require some extra work on my end.  If anyone has experience setting up CI for publishing to multiple platforms and wants to share I would love to hear details.

A couple of options until this is fixed:
- include source
- clone repo and publish to local maven

**Comment by patjackson52** [comment]
@mpetuska v0.5.2 was just released with all platforms published to maven central.  Can you verify this is working for you?
