### ISSUE TITLE
CombineEnhancers

### ISSUE THREAD

**Issue by jason-whitted** [reduxkotlin/redux-kotlin#45]
What is the purpose of [combineEnhancers](https://github.com/reduxkotlin/redux-kotlin/blob/master/lib/src/commonMain/kotlin/org/reduxkotlin/CombineEnhancers.kt)?

It's not documented and does not have an analog in JS redux. I don't see it used anywhere -- this appears that it may be debris.

**Comment by patjackson52** [comment]
Yes, I believe this was some code that was used early on and never got deleted.  Combining reducers can be completed with the provided `compose` function.

Removing with this PR: https://github.com/reduxkotlin/redux-kotlin/pull/47

Thanks for reporting 💯
