### ISSUE TITLE
createThreadSafeStore support WASM & linArm32

### ISSUE THREAD

**Issue by patjackson52** [reduxkotlin/redux-kotlin#54]
Currently not supported due to atomicFu not supporting.  It is on the roadmap for AtomicFu.  This requires no action on our part, other than updating when available.

https://github.com/Kotlin/kotlinx.atomicfu/issues/142#issuecomment-644603946

**Comment by mpetuska** [comment]
linArm32 and wasm32 targets got deprecated now
