### ISSUE TITLE
Empty artifact in maven central (?)

### ISSUE THREAD

**Issue by dudududi** [reduxkotlin/redux-kotlin#8]
Hi,

I have tried to download and use your library in my test multiplatform project. I have added your dependency in my build.gradle.kts like follow:
```
    sourceSets {
        commonMain {
            dependencies {
                api("org.jetbrains.kotlin:kotlin-stdlib-common")
                api("org.reduxkotlin:redux-kotlin:0.2.4")
            }
        }
   }
```

However, I am still unable to use it on in my code - references to APIs functions cannot be found. Any ideas?

**Comment by patjackson52** [comment]
Closed due to unable to reproduce.

**Comment by Jturpijn** [comment]
I'm sorry in advance for if I'm doing something stupid, but I'm getting the same unresolved issue. I've updated gradle to 6.1 and I've also added the `enableFeaturePreview('GRADLE_METADATA')`.  

build.gradle.kts :
```
kotlin {   
    sourceSets {  
        main {  
            dependencies {  
                implementation("org.reduxkotlin:redux-kotlin:0.3.1")  
            }  
        }  
    }  
}
```
